# Generated by Django 4.2.20 on 2025-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_application_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
