# Generated by Django 4.2.20 on 2025-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_customuser_agent_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='commission',
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
