# Generated by Django 4.2.20 on 2025-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_interest_assigned_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
