# Generated by Django 4.2.20 on 2025-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigning', 'Assigning…'), ('assigned', 'Assigned')], default='pending', max_length=20),
        ),
    ]
