# Generated by Django 4.2.20 on 2025-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('sold', 'Sold'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
