# Generated by Django 4.2.20 on 2025-04-28 07:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrating',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='properties.transaction'),
        ),
        migrations.AlterField(
            model_name='agentrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='agentrating',
            unique_together={('transaction', 'user')},
        ),
    ]
