# Generated by Django 4.2.20 on 2025-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_agentrating_transaction_alter_agentrating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
